### ISSUE TITLE
Missing "List Exfiltrated Data" menu in UI

### ISSUE THREAD

**Issue by whid-injector** [whid-injector/WHID-Mobile-Connector#1]
I noticed is missing the "List Exfiltrated Data" submenu in the UI.

The one pointing at this URL http://192.168.1.1/exfiltrate/list

![image](https://user-images.githubusercontent.com/26245612/60709086-44929780-9f18-11e9-9a3b-606a28316e29.png)

![image](https://user-images.githubusercontent.com/26245612/60709096-4cead280-9f18-11e9-9545-df91caaa4875.png)

**Comment by PaulSec** [comment]
Hey there, 

This shouldn't be too hard to do (still need to check) but I guess that I would just have to retrieve this table and access the different file contents. 

I will keep you posted about this!

**Comment by minkione** [comment]
Forgot to ask... is this implemented already? :)

**Comment by PaulSec** [comment]
Hey hey @whid-injector  and @minkione, I worked on the feature. 
Would it be possible for you to check this build and download the APK here: https://github.com/whid-injector/WHID-Mobile-Connector/actions/runs/65231312

Basically you should: 
- Have a new "Exfiltrated Payloads" (I reckon the name sucks and I will s/Payloads/Data/g). 
- Should be able to click on any payload in the list
- Redirect you to a new page with the exfiltrated payload

Let me know if that works for you, if so, I will merge this into master, sign a new APK and push it on the store.

**Comment by whid-injector** [comment]
All good Sir! Works like charm!
Thanks Paul for the update! 😍

**Comment by whid-injector** [comment]
Closing since resolved. Thanks again mate!
