### ISSUE TITLE
We cannot close the side menu

### ISSUE THREAD

**Issue by LupyXev** [whid-injector/WHID-Mobile-Connector#20]
**Describe the bug**
The side menu (with differents features) is not closable, even if I push in screen's right part

**Android OS version**
Android 10 (kali nethunter / Lineage 17) 

**WHID version**
0.0.3

**To Reproduce**
Only install the app with kali nethunter store (a F-Droid) and open side menu

**Expected behavior**
A side menu that can close

**Comment by HugoMskn** [comment]
Have you tried on a latest version of WHID ?

**Comment by LupyXev** [comment]
I don't use it anymore, so I can't answer sorry
