### ISSUE TITLE
White screen on WHID mobile connector app.

### ISSUE THREAD

**Issue by Krack1n** [whid-injector/WHID-Mobile-Connector#7]
Hi,
I am using a nexus 5 version 6.0.1 build number M4B30Z rooted with kali nethunter installed on it and my WHID connector app version 0.0.2 has stopped working. When I open it all it shows is a the logo and then a blank white screen instead of opening to the main menu screen. Any one have any ideas on how to fix this?
Thank you.

**Comment by PaulSec** [comment]
Do you have access to the logcat to have an idea what can possibly go wrong? Any stack trace in this?

**Comment by Krack1n** [comment]
Yeah hope this can help. 
[log.txt](https://github.com/whid-injector/WHID-Mobile-Connector/files/4113230/log.txt)

**Comment by PaulSec** [comment]
Thanks, that will help me troubleshooting and I will try to make you sorted asap

**Comment by Krack1n** [comment]
Yes the splash screen pops up then it goes straight to the white screen.

**Comment by PaulSec** [comment]
Hi, 

it seems some other people have the same issue with some old browser version, see https://github.com/ionic-team/ionic/issues/16873

And you can see that those files in `polyfills.ts` are commented here: https://github.com/whid-injector/WHID-Mobile-Connector/blob/master/src/polyfills.ts

I commented them out, build a new app and pushed it here : https://drive.google.com/open?id=1pxUOc9IGyiXUvMP-z-9gm7rgb0W6e7Yz

Can you : 
1. uninstall your current version
2. download and install this version
3. give us your feedback

Thanks a lot in advance

**Comment by Krack1n** [comment]
Okay I installed the new version and now it is not and the app starts but I cannot interact with anything on screen, its just frozen but doesn't crash or white screen now.

**Comment by PaulSec** [comment]
Alright, we're getting there!

I found https://forum.ionicframework.com/t/after-splash-screen-display-white-screen-long-time/80162/21 and I added this code snippet in `config.xml` :

```
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="SplashScreenDelay" value="10000" />
    <preference name="FadeSplashScreenDuration" value="1000" />
    <preference name="SplashScreen" value="screen" />
    <preference name="ShowSplashScreen" value="true" />
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="FadeSplashScreen" value="true" />
```


Here is a new link for the app: https://drive.google.com/open?id=1blaRK7YsXq5fr1NdHUkqu-EqqgiPtqiw
The splash screen should be longer than before, don't worry about that.

Can you try again (uninstall/download/launch) and tell me how things are going? 

Thanks again!

**Comment by Krack1n** [comment]
Alright the new version doesn't 
![Whid](https://user-images.githubusercontent.com/59591806/73132488-f1974380-4013-11ea-8779-a00677027239.png)
white screen and the splash screen is longer but there is still no interaction the screen is just frozen. Attached image is how it looks.

**Comment by PaulSec** [comment]
Mmh.. It's intriguing. I will need to investigate why buttons etc. are not properly rendered (based on the shape + CSS etc) and I guess this is why you can't click on anything. 

Thanks again and sorry for experiencing this kind of issue!

**Comment by Krack1n** [comment]
Its no problem, thank you for all the help in attempting to fix it!

**Comment by PaulSec** [comment]
No prob, this seems some bug with Android < 7 but I will investigate more during the week-end, I will keep you posted with this!

**Comment by PaulSec** [comment]
Hi, again, it's me. 

I believe this has to come with WebView. Without going too much in details, ionic apps (such as the WHID app) are HTML/JS apps which are embedded in webviews. 
If you have the chance, could you update your Android System Webview (https://www.apkmirror.com/apk/google-inc/android-system-webview/) and check if it works better? 

I think it should help you out.

**Comment by Krack1n** [comment]
Yes that is seemed to fix it! No white screen, no crash and all touch interactions are working now!

**Comment by PaulSec** [comment]
Oh mate, this is awesome!

Let's keep this issue open and I will udpate the README for Android < 7 to make sure that everyone updates their Android System Webview. 

Thanks again!

**Comment by Krack1n** [comment]
Thank you for all the help, glad that it is woeking now!
